version: "2"

linters:
  default: none
  enable:
    - staticcheck
    - govet
    - unused
    - forbidigo
  exclusions:
    rules:
      - linters:
        - staticcheck
        text: "QF1008:"
      - linters:
          - staticcheck
        text: "QF1007:"
      - linters:
          - staticcheck
        text: "QF1010:"
formatters:
  enable:
    - gofmt
