on:
  workflow_call:
name: Tests
jobs:
  get-go-versions:
    name: Collect available Go versions
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.versions.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - uses: arnested/go-version-action@13d01fa2f867e8a08e9f8197def5f2da5a11ab6d
        id: versions

  run:
    strategy:
      fail-fast: false # Keep running if one leg fails.
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ${{ fromJSON(needs.get-go-versions.outputs.matrix) }}
    runs-on: ${{ matrix.os }}
    needs: get-go-versions
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup - Go ${{ matrix.go-version }}
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753
        with:
          go-version: ${{ matrix.go-version }}

      - name: Setup - Python
        uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "requirements-test.txt"

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade -r requirements-test.txt

      - name: Run tests
        run: go test -race -covermode atomic -coverprofile='profile.cov' ./...

      - name: Send coverage
        uses: shogo82148/actions-goveralls@df920a6a2468668dfcf71a0b43817f89eaa5ea04
        with:
          path-to-profile: profile.cov
          flag-name: Go-${{ matrix.go-version }}
          parallel: true

  golangci:
    strategy:
      matrix:
        go-version: ${{ fromJSON(needs.get-go-versions.outputs.matrix) }}
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    needs: get-go-versions
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: golangci-lint ${{ matrix.go-version }} ${{ matrix.os }}
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
          args: --timeout 5m --verbose
